# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
    depends_on:
      - mongo

  adminer:
    image: adminer
    ports:
      - 8080:8080

  example:
    volumes:
      - "./:/usr/src/dbexample"
      # - "./usr/src/dbexample/node_modules"
    build: .
    command: ["npm","run","listen"]
    depends_on:
      - db